### ISSUE TITLE
Feature Request - Configuration options

### ISSUE THREAD

**Issue by RhythmicSys** [voidtask/TwitchChatReader#1]
It would be really nice to be able to customize the style and colors of the different formatted chat types

**Comment by voidtask** [comment]
@RhythmicSys sure! Could you give some examples?

**Comment by RhythmicSys** [comment]
Sure
The ability to change these values in a config would be nice:
**Ability to add a prefix before all chat that comes in (like [twitch]) and a color**
![image](https://github.com/httpolar/TwitchChatReader/assets/45906780/8f2900d2-7aee-4d6b-8760-7d49c860db0f)


**Mod emoji/prefix and color:**
![image](https://github.com/httpolar/TwitchChatReader/assets/45906780/fbdb2e7c-e55b-4dd3-9d5a-df48da71c976)

**Sub emoji/prefix and color:**
![image](https://github.com/httpolar/TwitchChatReader/assets/45906780/c894735e-b2fb-406b-9a12-1e5d371001c3)

**Chat color:**
![image](https://github.com/httpolar/TwitchChatReader/assets/45906780/890b9ed3-c437-4e57-a654-4df60e1e85f7)

I was trying to modify this with my own values but intelliJ did not want to resolve the dependencies lol


![image](https://github.com/httpolar/TwitchChatReader/assets/45906780/4f0a5149-8393-4bf3-81af-d730fd5a7c22)

But yeah, those values being configurable instead of set specifically within the code would be awesome ^-^

**Comment by voidtask** [comment]
Thank you! Alright then, I'll try implementing some sort of configuration soon-ish

**Comment by voidtask** [comment]
Extremely sorry it's taking so long! I've been super busy lately with my graduation at university coming soon, I do remember about this request.

**Comment by RhythmicSys** [comment]
No worries!

**Comment by voidtask** [comment]
I'm finally free! Although this is probably not even  needed anymore, now I have quite a lot of time and will be able to implement this feature and also upgrade the mod to support newer versions of the game

**Comment by voidtask** [comment]
I've updated the mod to 1.21 and also included a configuration file which allows you to set custom prefixes (not all of them are working as of now tho, but mods, subs and global prefixes should)

**Comment by voidtask** [comment]
For ease of use commands were implemented!
