### ISSUE TITLE
Feature Request: "Better color for prefixes"

### ISSUE THREAD

**Issue by Palxz** [voidtask/TwitchChatReader#3]
It would be cool if prefixes were able to also handle the "&#FFFFFF" format for custom HexColors, just so you are not limited by minecraft's default colors.

**Comment by voidtask** [comment]
I'll look into this!

**Comment by voidtask** [comment]
I honestly have no idea how does this even work in Minecraft, looked into Fabric API multiple times now and I just feel so lost, ngl modding api documentation is the worst documentation I've ever touched so far. I'll probably have to create my own utility to parse such format and turn that into Minecraft's Text with the desired colors, it feels so weird that Minecraft has a built in function to parse standard colors as Text but there is just nothing which could help with HEX formats

**Comment by voidtask** [comment]
Alright I think I did it, will be making a release soon!

**Comment by voidtask** [comment]
Implemented, you can find the new version on Modrinth with the support for this feature
